name: Checks
on:
  - push

jobs:
  checks:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install && cd tests && yarn install
      - name: Build package
        run: |
          yarn build
          ls -la ./dist
      - name: Run tests
        run: |
          yarn test
